### ISSUE TITLE
CPU consumption increases to max if Devolo device is unplugged

### ISSUE THREAD

**Issue by james-h-dt** [2Fake/devolo_plc_api#132] opened 2023-05-25 15:40 UTC
**Describe the bug**
Device CPU consumption grows from 2% to 100% within 24 hours IF:

- Devolo integration enabled by auto-discovery AND
- Several Devolo devices found AND
- at least one Devolo device is then unplugged.

The key bit is unplugging a discovered device. This leads to the steady CPU consumption.

**Used device**

Home Assistant Core (Apr 2023) running inside Docker container on Raspberry Pi3 under Arch (Apr 2023).

**To Reproduce**

As above.

**Expected behavior**

CPU remains low and does not increase when Devolo devices are unplugged or plugged back in.

**Additional context**

Workaround for me was:

- Disable the unplugged devices, using the standard hass features.
- Restart hass. 

CPU consumption went back to normal, measured over 24 hours.

Also, disabling the unplugged devices without a restart may help a little. 

(Over a 15 minute test, the CPU seemed to improve slightly although did not properly recover in that time.)

Traced to Devolo API, thanks to great advice from bdraco/J. Nick Koston.

**Comment by james-h-dt** [comment] 2023-05-25 15:47
See also [hass forum thread here](https://community.home-assistant.io/t/cpu-consumption-keeps-growing-to-max-every-24h/574108/15). Has some images, showing CPU consumption over time.

**Comment by Shutgun** [comment] 2023-05-25 16:23
Hi @james-h-dt , thanks for bringing that to our attention. Could you tell me which device types you use and especially which one you unplug? I have a Magic 2 Wifi that falls asleep at night and a Repeater 5400 that is sometimes hard to reach by out integration and yet I'm not seeing that effect...

Also: did you try exchanging the library as bdraco suggested? I reworked the code that py-spy spotted recently and there are chances, that the issue was fixed by accident. If not, I'll try to reproduce the issue locally, so you don't have to fool around with your setup.

**Comment by Shutgun** [comment] 2023-05-25 16:41
Firmware versions of your device might also be interesting.

**Comment by james-h-dt** [comment] 2023-05-25 17:24
Hi Guido, and good hearing from you.

Here's the info you asked for:

   - Devices are all Devolo Magic 1 LAN Powerline 1200
      - Five devices in total, with two unplugged.
      - Firmware versions are all: 7.12.9.142 (2023-05-02)
      - Firmware self-upgrade feature is on.
   - I did not try exchanging the library. This task is beyond my skillset.
   - I do have some general IT technical experience. If you could provide
   some simple steps for me to follow, I'd be happy trying the library.


Best wishes,

James.
*e*: ***@***.***

**Comment by Shutgun** [comment] 2023-05-25 18:28
I don't have that particular device at hand, but how I currently understand the issue, it shouldn't make any difference. I added another Wifi to my production Home Assistant and unplugged it. So by tomorrow morning I should see an increase of memory usage and/or CPU usage. If so, I will update the library to see if it is fixed already. If not, I will try to organize a Magic LAN 1 for testing.

**Comment by Shutgun** [comment] 2023-05-26 08:28
My contact at devolo seems to face the exact same issue. The new version is now running in his setup. I will keep you updated :+1:

**Comment by Shutgun** [comment] 2023-06-06 15:45
So it seems, that the new version does not help here. However, I now tried a few things and even have a second instance of Home Assistant running, that has all my devices included but a firewall rule prevents HA accessing them. Still I am not able to reproduce the issue.

@bdraco: you offered your help in case this happens. Do you have some advice what I could check or try?

**Comment by bdraco** [comment] 2023-06-07 01:58
I'm going to be traveling until the 24th so my availability is a bit light right now. I'll try to find some time before I get back home.

**Comment by Shutgun** [comment] 2023-07-13 17:49
Hi @bdraco , I hope you returned save. Is your offer still valid?

**Comment by bdraco** [comment] 2023-07-13 18:12
I should be back home in about an hour if you want to reach out on discord

**Closed** 2023-07-13 19:52 UTC
